stages:
  prepare:
    cmd: python 2_prepare.py
    deps:
    - 2_prepare.py
    - data/wine.csv
    params:
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python 3_train_pipeline.py
    deps:
    - 3_train_pipeline.py
    - data/prepared/wine_test.csv
    - data/prepared/wine_train.csv
    params:
    - train.seed
    outs:
    - data/metrics
    - models/trained
