stages:
  prepare:
    cmd: python src/pipeline/prepare.py
    deps:
    - data/wine.csv
    - src/pipeline/prepare.py
    params:
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python src/pipeline/train.py
    deps:
    - data/prepared/wine_test.csv
    - data/prepared/wine_train.csv
    - src/pipeline/train.py
    params:
    - train.max_iter
    - train.seed
    outs:
    - metrics/train
    - models/trained
  evaluate:
    cmd: python src/pipeline/evaluate.py
    deps:
    - data/prepared/wine_test.csv
    - models/trained/model.joblib
    - src/pipeline/evaluate.py
    metrics:
    - metrics/test/scores.json:
        cache: false
    plots:
    - metrics/test/metrics.json:
        cache: false
