stages:
  prepare:
    cmd: python 2_prepare.py
    deps:
    - 2_prepare.py
    - data/wine.csv
    params:
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python 3_train_pipeline.py
    deps:
    - 3_train_pipeline.py
    - data/prepared/wine_test.csv
    - data/prepared/wine_train.csv
    params:
    - train.max_iter
    - train.seed
    outs:
    - data/metrics
    - models/trained
  evaluate:
    cmd: python 4_evaluate.py
    deps:
    - 4_evaluate.py
    - data/prepared/wine_test.csv
    - models/trained/model.joblib
    metrics:
    - data/metrics_threshold/scores.json:
        cache: false
    plots:
    - data/metrics_threshold/metrics.json:
        cache: false
        x: recall
        y: precision
